blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/voltaflow/dns_terraform_module/blob/main/README.md
    about: Read the complete documentation
  - name: 💬 GitHub Discussions
    url: https://github.com/voltaflow/dns_terraform_module/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Examples
    url: https://github.com/voltaflow/dns_terraform_module/tree/main/examples
    about: View example configurations for each provider
