name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Provider Scope
      description: Which provider(s) would this feature affect?
      options:
        - AWS Route53
        - Cloudflare
        - Vercel
        - All providers
        - New provider
        - Core module
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it enable?
      placeholder: I'm trying to accomplish... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought about

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you'd like to use this feature
      render: hcl
      placeholder: |
        module "dns" {
          source = "github.com/voltaflow/dns_terraform_module"
          # Your example configuration
        }

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Cannot use module without this
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: I am willing to help implement or test this feature
          required: false
        - label: This feature aligns with the module's goals
          required: true
